### ISSUE TITLE
NutFilePool初始化多次

### ISSUE THREAD

**Issue by shi-yuan** [nutzam/nutz#1099]
本机Temp文件夹是空的。
上传文件，NutFilePool初始化多次:
`13:36:18 NutFilePool INFO  Init file-pool by: C:\Users\admin\AppData\Local\Temp [2000]
13:36:18 NutFilePool INFO  file-pool.cursor: 121
13:36:18 NutFilePool INFO  Init file-pool by: C:\Users\admin\AppData\Local\Temp [2000]
13:36:18 NutFilePool INFO  file-pool.cursor: 121
13:36:18 NutFilePool INFO  Init file-pool by: C:\Users\admin\AppData\Local\Temp [2000]
13:36:18 NutFilePool INFO  file-pool.cursor: 121
13:36:18 NutFilePool INFO  Init file-pool by: C:\Users\admin\AppData\Local\Temp [2000]
13:36:18 NutFilePool INFO  file-pool.cursor: 121
13:36:18 NutFilePool INFO  Init file-pool by: C:\Users\admin\AppData\Local\Temp [2000]
13:36:18 NutFilePool INFO  file-pool.cursor: 121
13:36:18 NutFilePool INFO  Init file-pool by: C:\Users\admin\AppData\Local\Temp [2000]
13:36:18 NutFilePool INFO  file-pool.cursor: 121
13:36:18 NutFilePool INFO  Init file-pool by: C:\Users\admin\AppData\Local\Temp [2000]
13:36:18 NutFilePool INFO  file-pool.cursor: 121
13:36:18 NutFilePool INFO  Init file-pool by: C:\Users\admin\AppData\Local\Temp [2000]
13:36:18 NutFilePool INFO  file-pool.cursor: 121
...
java.lang.RuntimeException: org.nutz.mvc.upload.UploadException: java.io.FileNotFoundException: C:\Users\admin\AppData\Local\Temp\00\00\00\00\00\00\00\7A.pdf (请求的操作无法在使用用户映射区域打开的文件上执行。)
	at org.nutz.lang.Lang.wrapThrow(Lang.java:153)
	at org.nutz.mvc.upload.UploadAdaptor.getReferObject(UploadAdaptor.java:202)
	at org.nutz.mvc.upload.UploadAdaptor.getReferObject(UploadAdaptor.java:61)
	at org.nutz.mvc.adaptor.AbstractAdaptor.adapt(AbstractAdaptor.java:226)
	at org.nutz.mvc.upload.UploadAdaptor.adapt(UploadAdaptor.java:116)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.ActionFiltersProcessor.process(ActionFiltersProcessor.java:58)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.EncodingProcessor.process(EncodingProcessor.java:27)
	at org.nutz.mvc.impl.NutActionChain.doChain(NutActionChain.java:44)
	at org.nutz.mvc.impl.ActionInvoker.invoke(ActionInvoker.java:67)
	...
Caused by: org.nutz.mvc.upload.UploadException: java.io.FileNotFoundException: C:\Users\admin\AppData\Local\Temp\00\00\00\00\00\00\00\7A.pdf (请求的操作无法在使用用户映射区域打开的文件上执行。)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.nutz.lang.born.ConstructorBorning.born(ConstructorBorning.java:17)
	at org.nutz.lang.born.BornContext.doBorn(BornContext.java:60)
	at org.nutz.lang.Mirror.born(Mirror.java:990)
	at org.nutz.lang.Lang.wrapThrow(Lang.java:169)
	at org.nutz.mvc.upload.FastUploading.parse(FastUploading.java:223)
	at org.nutz.mvc.upload.UploadAdaptor.getReferObject(UploadAdaptor.java:185)
	... 34 more
Caused by: java.io.FileNotFoundException: C:\Users\admin\AppData\Local\Temp\00\00\00\00\00\00\00\7A.pdf (请求的操作无法在使用用户映射区域打开的文件上执行。)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.nutz.mvc.upload.FastUploading.parse(FastUploading.java:161)
	... 35 more`

**Comment by wendal** [comment]
请为不同的upload方法指定不同的临时目录路径

**Comment by shi-yuan** [comment]
用的是同一个upload方法

**Comment by shi-yuan** [comment]
上传文件：
`Arrays.stream(new File(filePath).listFiles()).parallel()
                .forEach(file -> {
                    if (!file.isHidden()) {
                        upfile(file.getAbsolutePath());
                    }
                });`

**Comment by wendal** [comment]
用的是ioc吧? 把upload.js贴一下, NutFilePool应该用单例的

**Comment by shi-yuan** [comment]
IOC里没有配置

**Comment by wendal** [comment]
那把入口方法的声明贴一下

**Comment by shi-yuan** [comment]
`@AdaptBy(type = UploadAdaptor.class)
    public Object upload(@Param("file") TempFile file) throws Exception {
        ...
    }`

**Comment by wendal** [comment]
版本是啥, 难道是Module类不是单例的??? 把Module类的声明也贴一下

**Comment by shi-yuan** [comment]
1.r.57

**Comment by shi-yuan** [comment]
Module类是单例的

**Comment by wendal** [comment]
那就不知道, 尝试用最小代码重现之

**Comment by shi-yuan** [comment]
我试试，谢谢！

**Comment by wendal** [comment]
找到原因了?

**Comment by shi-yuan** [comment]
看日志，注解的处理器@AdaptBy(type = UploadAdaptor.class)，初始化了多次，应该是我这边的问题
