### ISSUE TITLE
NutServlet中的一个bug (1.r.57)

### ISSUE THREAD

**Issue by whitemay** [nutzam/nutz#1104]
我使用的是NutServlet，估计这个大家用的比较少，所以没人报这个错误。
在使用Shiro，引入SessionProvider的时候，系统报空指针错。（NutServlet第57行）

我看了一下，原代码是：

`req = sp.filter(req, resp, getServletContext());`

我推测这里应该是：

`req = sp.filter(req, resp, prCtx);`

改过来之后，错误消失。
具体是否应该这样修改，请指正。

**Comment by wendal** [comment]
哦, getServletContext 抛NPE? 奇怪

**Comment by whitemay** [comment]
或者是应该改为?

`req = sp.filter(req, resp, Mvcs.getServletContext());`

**Comment by whitemay** [comment]
Nutz现在的机制就是使用Mvcs里面的servletContext，那原来的Servlet基类中的servletContext为空也不奇怪吧。
而且NutFilter里面，类似位置的语句也是Mvcs.getSevletContext()。

**Comment by wendal** [comment]
贴一下报错堆栈信息你, 总觉得是其他原因

**Comment by whitemay** [comment]
`严重: Servlet.service() for servlet [nutz] in context with path [/Servlet.NZ] threw exception [Filtered request failed.] with root cause
java.lang.NullPointerException
	at javax.servlet.GenericServlet.getServletContext(GenericServlet.java:125)
	at org.nutz.mvc.NutServlet.service(NutServlet.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by wendal** [comment]
好吧,的确很神奇
