### ISSUE TITLE
ioc注入的错误

### ISSUE THREAD

**Issue by ansjsun** [nutzam/nutz#1133]
版本

nutz-1.r.57.r3.jar
mongo-java-driver-3.2.2.jar
nutzmongo-1.r.57-20160602.132719-1.jar

Ioc.js
````
var ioc = {
	zMongo : {
		type : "org.nutz.mongo.ZMongo" ,
		args : [ "xxxx", 27017 ], // 或者不写参数，默认就是127.0.0.1和27017
		factory : "org.nutz.mongo.ZMongo#me"
	},
	zMoDB : {
		args : [ "xxx_mobile" ], // 数据库名称
		factory : "$zMongo#db"
	},
	zMoCoUser : {
		args : [ "user" ],
		factory : "$zMoDB#c"
	},
	zMoCoMessage : {
		args : [ "message" ],
		factory : "$zMoDB#c"
	}
	
};

````

code

````
Ioc ioc = new NutIoc(new JsonLoader("src/test/resources/ioc.js"));
		
		
		ZMoCo zMoCoUser = ioc.get(ZMoCo.class,"zMoCoUser")  ;

		System.out.println(zMoCoUser);
````

error

````
log4j:WARN No appenders could be found for logger (org.nutz.resource.Scans).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" org.nutz.ioc.IocException: [zMoCoUser, zMoDB] # NULL TYPE object 'zMoDB'
	at org.nutz.ioc.impl.NutIoc.get(NutIoc.java:199)
	at org.nutz.ioc.impl.NutIoc.get(NutIoc.java:239)
	at org.nutz.ioc.impl.ObjectMakerImpl$1.born(ObjectMakerImpl.java:88)
	at org.nutz.ioc.weaver.DefaultWeaver.born(DefaultWeaver.java:67)
	at org.nutz.ioc.impl.ObjectMakerImpl.make(ObjectMakerImpl.java:114)
	at org.nutz.ioc.impl.NutIoc.get(NutIoc.java:210)
	at org.nutz.ioc.impl.NutIoc.get(NutIoc.java:239)
	at cn.com.infcn.mobile.UserApi.main(UserApi.java:29
````

如果这么写

````
public static void main(String[] args) {
		
		Ioc ioc = new NutIoc(new JsonLoader("src/test/resources/ioc.js"));
		
		ZMongo zMongo = ioc.get(ZMongo.class,"zMongo") ;
		
		ZMoDB zMoDB = ioc.get(ZMoDB.class,"zMoDB")  ;
		
		ZMoCo zMoCoUser = ioc.get(ZMoCo.class,"zMoCoUser")  ;

		System.out.println(zMoCoUser);

	}
````

就不报错

**Comment by wendal** [comment]
fix in a591197cd445ceee07cd695def7fd960b5baaa92

已经改好了的, 老版本依然需要声明type.
