### ISSUE TITLE
H2数据库 Daos.migration 自动增减字段时调用 检查索引时(checkIndex) 报异常

### ISSUE THREAD

**Issue by jiyuefeng** [nutzam/nutz#1248]
Nutz版本号：1.r.60 在调用Daos.migration时 如果数据为H2。报异常：

`org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT [*]"; expected "TOP, LIMIT, DISTINCT, ALL, *, NOT, EXISTS, INTERSECTS"; SQL statement:
show index from sys_user_roles [42001-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.message.DbException.getSyntaxError(DbException.java:205) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.getSyntaxError(Parser.java:537) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.readTerm(Parser.java:2965) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.readFactor(Parser.java:2320) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.readSum(Parser.java:2307) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.readConcat(Parser.java:2277) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.readCondition(Parser.java:2127) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.readAnd(Parser.java:2099) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.readExpression(Parser.java:2091) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.parseSelectSimpleSelectPart(Parser.java:2003) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2035) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.parseSelectSub(Parser.java:1890) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1711) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.parseSelect(Parser.java:1699) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.parsePrepared(Parser.java:445) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.parse(Parser.java:317) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.parse(Parser.java:293) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.prepare(Parser.java:238) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.engine.Session.prepare(Session.java:525) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.engine.Session.prepare(Session.java:512) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.prepare(Parser.java:985) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.parseShow(Parser.java:977) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.parsePrepared(Parser.java:455) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.parse(Parser.java:317) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.parse(Parser.java:289) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.command.Parser.prepareCommand(Parser.java:254) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.engine.Session.prepareLocal(Session.java:560) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.engine.Session.prepareCommand(Session.java:501) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1202) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73) ~[h2-1.4.192.jar:1.4.192]
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:290) ~[h2-1.4.192.jar:1.4.192]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126) ~[tomcat-jdbc-8.5.4.jar:na]
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108) ~[tomcat-jdbc-8.5.4.jar:na]
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81) ~[tomcat-jdbc-8.5.4.jar:na]
	at com.sun.proxy.$Proxy79.prepareStatement(Unknown Source) ~[na:na]
	at org.nutz.dao.impl.jdbc.AbstractJdbcExpert.getIndexNames(AbstractJdbcExpert.java:470) ~[nutz-1.r.60.jar:na]
	at org.nutz.dao.util.Daos$4.invoke(Daos.java:808) ~[nutz-1.r.60.jar:na]
`

经查询验证，是H2 数据库查询索引的语句异常，并不是
`show index from T_USER`
应为：
`SELECT * FROM INFORMATION_SCHEMA.INDEXES WHERE TABLE_NAME = 'T_USER';`

H2官方说明：
[http://www.h2database.com/html/grammar.html#show](http://www.h2database.com/html/grammar.html#show)

**Comment by jiyuefeng** [comment]
可在H2JdbcExpert 重写方法 getIndexNames

**Comment by wendal** [comment]
ok, 看看怎么改一下

**Comment by wendal** [comment]
@jiyuefeng 试试做个pull req?

**Comment by jiyuefeng** [comment]
@wendal OK

**Comment by wendal** [comment]
@jiyuefeng 期待你的pull req ^_^
