### ISSUE TITLE
Chain 的 add 方法传入时间戳时，组成的 sql 没加上引号的错误

### ISSUE THREAD

**Issue by ywjno** [nutzam/nutz#1260]
代码如下

```java
Timestamp ut = new Timestamp(System.currentTimeMillis());
nutDao.update(Community.class,
                              Chain.makeSpecial("position", "+1").add("updateTime", ut),
                              Cnd.where("position", ">=", newPosition)
                                 .and("position", "<", oldPosition)
                                 .and("publish", "=", true)
                                 .and("flag", "=", flag));
```
这是出现错误，提示
```
2017-05-16 16:47:42,359 [http-apr-8080-exec-10] DEBUG org.nutz.dao.impl.sql.run.NutDaoExecutor - UPDATE community SET `position`=`position`+1,`update_time`=2017-05-16 16:47:39.8  WHERE `position` >= ? AND `position`<? AND `publish`=? AND `flag`=?
    | 1 | 2 |    3 | 4 |
    |---|---|------|---|
    | 1 | 2 | true | 1 |
  For example:> "UPDATE community SET `position`=`position`+1,`update_time`=2017-05-16 16:47:39.8  WHERE `position` >= 1 AND `position`<2 AND `publish`=true AND `flag`='1'"
2017-05-16 16:47:42,466 [http-apr-8080-exec-10] DEBUG org.nutz.dao.impl.sql.run.NutDaoExecutor - SQLException
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '16:47:39.8  WHERE `position` >= 1 AND `position`<2 AND `publish`=1 AND `flag`='1' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

```
在更新 `update_time` 字段的时候没给值加上引号，所以出错了

**Comment by wendal** [comment]
不是引号,是没有走参数化
