### ISSUE TITLE
Dao拦截器，如何将拦截到的更新语句中的指定字段过滤掉

### ISSUE THREAD

**Issue by RoryWo** [nutzam/nutz#1325]
我的拦截器目的是实现，拦截update更新语句，然后然后自动补充上updateDateTime（当前时间）和updateBy（当前用户）的值，实体中本身带有这两个字段，而我下面的操作会导致更新的时候出现列重复

```java
 if (st.isUpdate() && st instanceof NutPojo) {
        	NutPojo np = (NutPojo) st;
			List<PItem> items = null;
			try {
				items = (ArrayList<PItem>) itemField.get(np);
				for (int i = 0; i < items.size(); i++) {
					if (items.get(i) instanceof UpdateFieldsPItem) {
						String uname = null;
						Subject subject = SecurityUtils.getSubject();
						if (subject != null) {
							uname = (String) subject.getSession().getAttribute(UserName.SessionUserName);
						}
//这种方式追加字段，会导致列重复
						items.add(i + 1, new Static(
								", updatetime = SYSDATE, updateby = " + ((null == uname) ? null : "'" + uname + "'")));
						
						break;
					}
				}
```

**Comment by RoryWo** [comment]
不瞒你说这个方法我试过，不过不知道是不是使用的方式不对，结果还是会有问题
我是这样用的
        DaoStatement st = chain.getDaoStatement();
	FieldMatcher matcher =new FieldMatcher();
	matcher.setLocked("^updatetime|updateby$");
	st.getContext().setFieldMatcher(matcher);
![image](https://user-images.githubusercontent.com/32186391/30732014-1b2157ea-9fa3-11e7-8b33-1304f05af282.png)
会出现这样的异常

**Comment by wendal** [comment]
报错信息贴一下

**Comment by RoryWo** [comment]
[DEBUG] 15:00:57.694 org.nutz.plugins.cache.dao.CachedNutDaoExecutor.exec(CachedNutDaoExecutor.java:194) - Clear Cache=base_aircraftcategory
org.nutz.dao.DaoException: java.lang.NullPointerException
	at org.nutz.dao.impl.sql.run.NutDaoRunner._runWithoutTransaction(NutDaoRunner.java:139)
	at org.nutz.dao.impl.sql.run.NutDaoRunner._run(NutDaoRunner.java:92)
	at org.nutz.dao.impl.sql.run.NutDaoRunner.run(NutDaoRunner.java:81)
	at org.nutz.dao.impl.DaoSupport.run(DaoSupport.java:245)
	at org.nutz.dao.impl.DaoSupport._exec(DaoSupport.java:257)
	at org.nutz.dao.impl.EntityOperator.exec(EntityOperator.java:55)
	at org.nutz.dao.impl.NutDao.update(NutDao.java:224)
	at com.panport.raiis.base.service.impl.AircraftCategoryServiceImpl.update(AircraftCategoryServiceImpl.java:39)
	at com.panport.raiis.base.module.AircraftCategoryModule.update(AircraftCategoryModule.java:115)
	at com.panport.raiis.base.module.AircraftCategoryModule$FM$update$b59694d6b1d1ffa52d2b22a14192a9a1.invoke(AircraftCategoryModule.java)
	at org.nutz.mvc.impl.processor.MethodInvokeProcessor.process(MethodInvokeProcessor.java:31)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.AdaptorProcessor.process(AdaptorProcessor.java:33)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.integration.shiro.NutShiroProcessor.process(NutShiroProcessor.java:126)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.ActionFiltersProcessor.process(ActionFiltersProcessor.java:58)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.ModuleProcessor.process(ModuleProcessor.java:123)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.EncodingProcessor.process(EncodingProcessor.java:27)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.UpdateRequestAttributesProcessor.process(UpdateRequestAttributesProcessor.java:15)
	at org.nutz.mvc.impl.NutActionChain.doChain(NutActionChain.java:44)
	at org.nutz.mvc.impl.ActionInvoker.invoke(ActionInvoker.java:67)
	at org.nutz.mvc.ActionHandler.handle(ActionHandler.java:31)
	at org.nutz.mvc.NutFilter.doFilter(NutFilter.java:202)
	at com.panport.raiis.nutz.mvc.SimpleNutFilter.doFilter(SimpleNutFilter.java:42)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:279)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.nutz.dao.impl.sql.run.NutDaoExecutor._runPreparedStatement(NutDaoExecutor.java:306)
	at org.nutz.dao.impl.sql.run.NutDaoExecutor.exec(NutDaoExecutor.java:90)
	at org.nutz.dao.DaoInterceptorChain.doChain(DaoInterceptorChain.java:66)
	at com.panport.raiis.nutz.util.UpdateDaoInterceptor.filter(UpdateDaoInterceptor.java:70)
	at org.nutz.dao.DaoInterceptorChain.doChain(DaoInterceptorChain.java:64)
	at org.nutz.dao.impl.interceptor.DaoLogInterceptor.filter(DaoLogInterceptor.java:22)
	at org.nutz.dao.DaoInterceptorChain.doChain(DaoInterceptorChain.java:64)
	at org.nutz.plugins.cache.dao.DaoCacheInterceptor._exec(DaoCacheInterceptor.java:28)
	at org.nutz.plugins.cache.dao.CachedNutDaoExecutor.exec(CachedNutDaoExecutor.java:187)
	at org.nutz.plugins.cache.dao.DaoCacheInterceptor.filter(DaoCacheInterceptor.java:18)
	at org.nutz.dao.DaoInterceptorChain.doChain(DaoInterceptorChain.java:64)
	at org.nutz.dao.DaoInterceptorChain.invoke(DaoInterceptorChain.java:139)
	at org.nutz.dao.impl.sql.run.NutDaoRunner.runCallback(NutDaoRunner.java:158)
	at org.nutz.dao.impl.sql.run.NutDaoRunner._runWithoutTransaction(NutDaoRunner.java:125)
	... 56 more

**Comment by wendal** [comment]
```
org.nutz.dao.impl.sql.run.NutDaoExecutor._runPreparedStatement(NutDaoExecutor.java:306)
```

奇怪,怎么会空指针呢,待我查查

**Comment by wendal** [comment]
把你的dao语句发一下, 还没能重现

**Comment by RoryWo** [comment]
好的更新语句吗，会被跟[DEBUG] 15:00:57.694 org.nutz.plugins.cache.dao.CachedNutDaoExecutor.exec(CachedNutDaoExecutor.java:194) - Clear Cache=base_aircraftcategory这个被清理导致的

**Comment by RoryWo** [comment]
UPDATE base_aircraftcategory SET categoryCode='A',description='A',remark='A',createby='NULL',updateby='NULL',createtime='2017-09-13 15:29:23',updatetime='NULL'  WHERE id='3608740ede1f44d085d6ebc4469784ce'

**Comment by wendal** [comment]
dao.XXX的java语句

**Comment by RoryWo** [comment]
int i = dao().update(aircraftcategory);
//下面这种直接在外面过滤在拦截是可以的，目前就是大部分采用上面这种方式，想看看能不能直接在拦截器中处理掉
int i=dao().update(aircraftcategory, FieldFilter.locked(AircraftCategory.class, "^updatetime|updateby$"));

**Comment by wendal** [comment]
贴一下你的dao.js, 我有点怀疑是拦截器顺序的问题

**Comment by RoryWo** [comment]
dao : {
            type : "org.nutz.dao.impl.NutDao",
            args : [{refer:"dataSource"}],
            fields : {
                //executor : {refer:"cacheExecutor"}
        		interceptors : [{refer:"cacheInterceptor"}, "log","com.panport.raiis.nutz.util.UpdateDaoInterceptor"] // 这是1.r.58及以上的写法
            }
        },

**Comment by RoryWo** [comment]
我拿到前面去好像就可以了额，谢谢大神了

**Comment by wendal** [comment]
神奇...
