### ISSUE TITLE
map.entrySet() 得到的对象无法 Json.toJson

### ISSUE THREAD

**Issue by ywjno** [nutzam/nutz#1382]
测试代码如下
```java
        Map<String, Integer> map = new HashMap<>();
        map.put("a", 1);
        map.put("b", 2);
        map.put("c", 3);
        System.out.println(Json.toJson(map.entrySet()));
```

控制台输出如下
```
Exception in thread "main" java.lang.IllegalAccessError: tried to access class java.util.HashMap$Node from class org.nutz.lang.reflect.fast.java.util.HashMap$Node$FM$getValue$ac4f54c2a1c33e9acd432354e380fa11
	at org.nutz.lang.reflect.fast.java.util.HashMap$Node$FM$getValue$ac4f54c2a1c33e9acd432354e380fa11.invoke(Node.java)
	at org.nutz.lang.eject.EjectByGetter.eject(EjectByGetter.java:33)
	at org.nutz.json.entity.JsonEntityField.getValue(JsonEntityField.java:173)
	at org.nutz.json.impl.JsonRenderImpl.pojo2Json(JsonRenderImpl.java:278)
	at org.nutz.json.impl.JsonRenderImpl.render(JsonRenderImpl.java:161)
	at org.nutz.json.impl.JsonRenderImpl.coll2Json(JsonRenderImpl.java:440)
	at org.nutz.json.impl.JsonRenderImpl.render(JsonRenderImpl.java:153)
	at org.nutz.json.Json.toJson(Json.java:239)
	at org.nutz.json.Json.toJson(Json.java:201)
	at org.nutz.json.Json.toJson(Json.java:187)
	at org.nutz.test.JsonTest.main(JsonTest.java:20)
```

**Comment by wendal** [comment]
貌似Node是非public类

**Comment by ywjno** [comment]
貌似结果不对啊，只输出了 value，没有 key
```
[{
   "value": 1
}, {
   "value": 2
}, {
   "value": 3
}]
```

**Comment by wendal** [comment]
不管了...

**Comment by ywjno** [comment]
=。=
