### ISSUE TITLE
NutzDao  insertOrUpdate(t) @Id的字段 id为包装器类型报错

### ISSUE THREAD

**Issue by JiGuangYuan** [nutzam/nutz#1408]
子类继承超类 @Id 字段， id为包装器类型，
调用  insertOrUpdate(t) 时，抛出异常

```
java.lang.RuntimeException: r u kidding me?! It is impossible!
	at org.nutz.lang.Lang.impossible(Lang.java:120)
	at org.nutz.dao.impl.sql.pojo.SingleColumnCondtionPItem.joinParams(SingleColumnCondtionPItem.java:61)
	at org.nutz.dao.impl.jdbc.NutPojo.getParamMatrix(NutPojo.java:82)
	at org.nutz.dao.impl.sql.NutStatement.forPrint(NutStatement.java:197)
	at org.nutz.dao.impl.sql.run.NutDaoExecutor.printSQL(NutDaoExecutor.java:388)
	at org.nutz.dao.impl.interceptor.DaoLogInterceptor.filter(DaoLogInterceptor.java:20)
	at org.nutz.dao.DaoInterceptorChain.doChain(DaoInterceptorChain.java:64)
	at org.nutz.dao.DaoInterceptorChain.invoke(DaoInterceptorChain.java:139)
	at org.nutz.integration.spring.SpringDaoRunner._run(SpringDaoRunner.java:18)
	at org.nutz.dao.impl.sql.run.NutDaoRunner.run(NutDaoRunner.java:82)
	at org.nutz.dao.impl.DaoSupport.run(DaoSupport.java:240)
	at org.nutz.dao.impl.DaoSupport._exec(DaoSupport.java:252)
	at org.nutz.dao.impl.NutDao.fetch(NutDao.java:617)
	at org.nutz.dao.impl.NutDao.insertOrUpdate(NutDao.java:1085)
	at org.nutz.dao.impl.NutDao.insertOrUpdate(NutDao.java:1067)
```

**Comment by wendal** [comment]
fix in 1995e5a20dd4c09138408c314e0440353eaaa8c9
