### ISSUE TITLE
ColType.MYSQL_JSON List转换问题

### ISSUE THREAD

**Issue by Rekoe** [nutzam/nutz#1410]
```java
import java.io.Serializable;
import java.util.List;

import org.nutz.dao.entity.annotation.ColDefine;
import org.nutz.dao.entity.annotation.ColType;
import org.nutz.dao.entity.annotation.Column;
import org.nutz.dao.entity.annotation.Id;
import org.nutz.dao.entity.annotation.Index;
import org.nutz.dao.entity.annotation.Table;
import org.nutz.dao.entity.annotation.TableIndexes;
import org.nutz.dao.entity.annotation.TableMeta;

@Table("question_detail")
@TableIndexes({ @Index(name = "sort_index", fields = { "sortId" }, unique = false) })
@TableMeta("{'mysql-charset':'utf8mb4'}")
public class QuestionDetail implements Serializable {

	private static final long serialVersionUID = 3678772162673735855L;

	@Id
	private int id;

	@Column(hump = true)
	private int sortId;

	@Column
	private String ask;

	@Column("answer")
	@ColDefine(customType = "json", type = ColType.MYSQL_JSON)
	private List<Answer> answers;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getSortId() {
		return sortId;
	}

	public void setSortId(int sortId) {
		this.sortId = sortId;
	}

	public String getAsk() {
		return ask;
	}

	public void setAsk(String ask) {
		this.ask = ask;
	}

	public List<Answer> getAnswers() {
		return answers;
	}

	public void setAnswer(List<Answer> answers) {
		this.answers = answers;
	}

}

```
转换的时候 提示
```

java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.rekoe.game.bean.Answer
	at com.rekoe.game.service.RoomService$2.run(RoomService.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Answer
```
public class Answer {

	private boolean right;
	private String answer;

	public boolean isRight() {
		return right;
	}

	public void setRight(boolean right) {
		this.right = right;
	}

	public String getAnswer() {
		return answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

}

```
data
```
[{ "right": true, "answer": "乔羽" }, { "right": false, "answer": "庄奴" }, { "right": false, "answer": "雷振邦" }, { "right": false, "answer": "刘白羽" }] 
```

**Comment by wendal** [comment]
看了看MysqlJsonAdaptor类, 没做转换的样子

**Comment by ywjno** [comment]
```
 * 注意，必要的时候需要给 POJO 添加<b>带一个参数的静态工厂方法</b>或者<b>带一个参数的构造函数</b>，<br>
 * 显示的使用 java.sql.ResultSet 来创建该 POJO，不然会出现无法映射的错误。
```

**Comment by Rekoe** [comment]
用 这个adaptor 属性来处理吧
