### ISSUE TITLE
JsonException没有保留异常信息

### ISSUE THREAD

**Issue by lihongjie0209** [nutzam/nutz#1428]
```
    @Test
    public void test_json_lost_exception_message() throws Exception {


        Pojo pojo = new Pojo();
        try {
            Json.toJson(pojo);

        } catch (Exception e) {


            assertEquals(e.getMessage(), pojo.message);

        }







    }


    public static class Pojo {


        String message = "this is my message";

        public String toJson() {

            throw new RuntimeException(message);
    }

    }


```

如果在toJson方法中抛出异常, 日志中只能看到JsonException, 但是对调试没有一点帮助, 希望可以把异常信息也输出

```
org.nutz.json.JsonException
	at org.nutz.json.entity.JsonEntity$1.toJson(JsonEntity.java:110)
	at org.nutz.json.impl.JsonRenderImpl.pojo2Json(JsonRenderImpl.java:266)
	at org.nutz.json.impl.JsonRenderImpl.render(JsonRenderImpl.java:161)
	at org.nutz.json.Json.toJson(Json.java:239)
	at org.nutz.mvc.Mvcs.write(Mvcs.java:291)


```

**Comment by lihongjie0209** [comment]
@wendal

**Comment by lihongjie0209** [comment]
jsonCallback = new JsonCallback() {
                public boolean toJson(Object obj, JsonFormat jf, Writer writer) throws IOException {
                    try {
                        if (paramCount == 0)
                            writer.write((String)toJsonMethod.invoke(obj));
                        else
                            writer.write((String)toJsonMethod.invoke(obj, jf));
                    }
                    catch (Exception e) {
                        throw new JsonException(err);

**Comment by lihongjie0209** [comment]
https://github.com/nutzam/nutz/blob/cb79895a2fe1b27ab6831d01fa6aa6a1b2bf6882/src/org/nutz/json/entity/JsonEntity.java#L101-L110


这里直接把异常给忽略了
