### ISSUE TITLE
EL表达式引擎负数问题

### ISSUE THREAD

**Issue by jqgsninimo** [nutzam/nutz#1475]
在表达式引擎中，表达式中包含负数时，会出现异常。

使用版本：1.r.68.v20190220

代码如下：

```java
import org.nutz.el.El;
import org.nutz.lang.Lang;
import org.nutz.lang.util.Context;

public class Test {
    public static void main(String[] args) throws Exception {
        Context context = Lang.context();
        context.set("Math", Math.class);
        Object max = El.eval(context, "Math.max(10, -11)");
        System.out.println(max);
    }
}
```

异常信息：

    Exception in thread "main" java.lang.NullPointerException
        at org.nutz.el.opt.object.MethodOpt.fetchMethod(MethodOpt.java:65)
        at org.nutz.el.opt.object.MethodOpt.calculate(MethodOpt.java:48)
        at org.nutz.el.opt.object.InvokeMethodOpt.calculate(InvokeMethodOpt.java:22)
        at org.nutz.el.arithmetic.RPN.calculate(RPN.java:55)
        at org.nutz.el.arithmetic.RPN.calculate(RPN.java:46)
        at org.nutz.el.El.eval(El.java:48)
        at Test.main(Test.java:9)

如果用括号将表达式中的负数括起来`Math.max(10, (-11))`，或者在负号前加零`Math.max(10, 0-11)`，程序可正常执行。

**Comment by zozoh** [comment]
看来是解析的问题 @juqkai 有空看看不

**Comment by jqgsninimo** [comment]
@wendal 
关于负数解析的问题，我同事和我发Issues重复了。
您在他的问题里判断原因是Math为非内置对象。
其实并非如此。
我提供了出现问题的代码，在使用表达式前已将`Math`设置到上下文中。
而且正如问题最后所述，将负数部分用括号括起来后，程序就能够正常运行。
所以当可判定问题是由其他原因导致的，很可能是表达式的解析存在问题。

**Comment by wendal** [comment]
给一下重现的代码?

**Comment by wendal** [comment]
眼瞎了...

**Comment by wendal** [comment]
@jqgsninimo 请验证

**Comment by jqgsninimo** [comment]
> @jqgsninimo 请验证

已使用`1.r.68.v20190329`版本验证通过，非常感谢🙏
