### ISSUE TITLE
UploadAdaptor 非单例报错

### ISSUE THREAD

**Issue by lihongjie0209** [nutzam/nutz#1490]
```
	@IocBean(name = "myUploadAdaptor", singleton = false)
	public UploadAdaptor uploadAdaptor(@Inject NutFilePool nutFilePool) {


		UploadingContext context = new UploadingContext(nutFilePool);
		context.setIgnoreNull(true);

		context.setMaxFileSize(2097152);

		context.setNameFilter("^(.+[.])(|jpg|png|xls|xlsx)$");

		return new UploadAdaptor(context);
	}

```

有两个地方使用,代码都一样

```

    @At("/api/upload/oss")
    @POST
    @AdaptBy(type = UploadAdaptor.class, args = {"ioc:myUploadAdaptor"})

```

```
java.lang.RuntimeException: org.nutz.mvc.upload.UploadException: Duplicate initialization is not allowed.
	at org.nutz.mvc.upload.UploadAdaptor.init(UploadAdaptor.java:213)
	at org.nutz.mvc.impl.processor.AdaptorProcessor.evalHttpAdaptor(AdaptorProcessor.java:46)
	at org.nutz.mvc.impl.processor.AdaptorProcessor.init(AdaptorProcessor.java:22)
	at org.nutz.mvc.impl.NutActionChainMaker.eval(NutActionChainMaker.java:38)
	at org.nutz.mvc.impl.UrlMappingImpl.add(UrlMappingImpl.java:54)
	at org.nutz.mvc.impl.NutLoading.evalUrlMapping(NutLoading.java:205)
	at org.nutz.mvc.impl.NutLoading.load(NutLoading.java:108)
	at org.nutz.boot.starter.nutz.mvc.NbMvcLoading.load(NbMvcLoading.java:28)
	at org.nutz.mvc.ActionHandler.<init>(ActionHandler.java:19)
	at org.nutz.mvc.NutFilter._init(NutFilter.java:91)
	at org.nutz.mvc.NutFilter.init(NutFilter.java:69)
	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:139)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:741)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:374)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:848)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:419)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:386)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.nutz.boot.starter.jetty.JettyStarter.start(JettyStarter.java:125)
	at org.nutz.boot.AppContext.startServers(AppContext.java:306)
	at org.nutz.boot.NbApp.execute(NbApp.java:204)
	at org.nutz.boot.NbApp.run(NbApp.java:177)
	at cn.boolin.MainLauncher.main(MainLauncher.java:291)
Caused by: org.nutz.mvc.upload.UploadException: Duplicate initialization is not allowed.
	... 31 more
```

**Comment by lihongjie0209** [comment]
@wendal

**Comment by wendal** [comment]
咦。。。 标注在方法上的@IocBean非单例，还真没测过
