### ISSUE TITLE
el的函数注册,在spring-boot上获取不到配置信息

### ISSUE THREAD

**Issue by fjcondy** [nutzam/nutz#1554]
spring-boot的jar的打包机制跟普通的不一样,CustomMake.me().register(fetchSelf(),this); 在加载时会到nutz.jar里面的找org/nutz/conf/NutzDefaultConfig.js 文件.   到spring-boot的nutz.jar是打包到自建的jar里面的. 导致加载失败.
`@Component
public class DigitalToVoice implements RunMethod {

	@Resource
	private VoiceTransferService voiceTransferService;
	public DigitalToVoice() {
		CustomMake.me().register(fetchSelf(),this);
	}
	private Log log=Logs.get();
	@Override
	public Object run(List<Object> fetchParam) {
		if(fetchParam.size()!=1) {
			log.errorf("digitalToVoice函数的输入参数非法:%s",fetchParam);
			return "";
		}
		String digitalStr=(String)fetchParam.get(0);
		return voiceTransferService.digitalConvert(digitalStr);
	}

	@Override
	public String fetchSelf() {
		return "digitalToVoice";
	}

}`

spring-boot启动报错.

`2020-07-25T11:28:59,926 [main                ] WARN                      org.nutz.conf.NutConf (   103) - Fail to load config?! for NutzDefaultConfig.js
java.lang.RuntimeException: java.io.FileNotFoundException: file:/home/c3tomcat/condy/aidm/aidm-0.0.2-SNAPSHOT.jar!/BOOT-INF/lib/nutz-1.r.61.r2.jar!/org/nutz/conf/NutzDefaultConfig.js
        at org.nutz.lang.Lang.wrapThrow(Lang.java:184) ~[nutz-1.r.61.r2.jar!/:1.r.61.r2]
        at org.nutz.lang.Streams.fileIn(Streams.java:509) ~[nutz-1.r.61.r2.jar!/:1.r.61.r2]
        at org.nutz.resource.impl.FileResource.getInputStream(FileResource.java:49) ~[nutz-1.r.61.r2.jar!/:1.r.61.r2]
        at org.nutz.resource.NutResource.getReader(NutResource.java:41) ~[nutz-1.r.61.r2.jar!/:1.r.61.r2]
        at org.nutz.conf.NutConf.loadResource(NutConf.java:88) [nutz-1.r.61.r2.jar!/:1.r.61.r2]
        at org.nutz.conf.NutConf.<init>(NutConf.java:63) [nutz-1.r.61.r2.jar!/:1.r.61.r2]
        at org.nutz.conf.NutConf.me(NutConf.java:55) [nutz-1.r.61.r2.jar!/:1.r.61.r2]
        at org.nutz.conf.NutConf.get(NutConf.java:120) [nutz-1.r.61.r2.jar!/:1.r.61.r2]
        at org.nutz.el.opt.custom.CustomMake.init(CustomMake.java:36) [nutz-1.r.61.r2.jar!/:1.r.61.r2]
        at org.nutz.el.opt.custom.CustomMake.<clinit>(CustomMake.java:28) [nutz-1.r.61.r2.jar!/:1.r.61.r2]
        at ecc.c3.dm.runMethod.dateToVoice.<init>(dateToVoice.java:28) [classes!/:0.0.2-SNAPSHOT]`

**Comment by fjcondy** [comment]
nutz的版本: 1.r.61.r2

**Comment by wendal** [comment]
换新版
