### ISSUE TITLE
jar嵌套调用报错

### ISSUE THREAD

**Issue by blueskeys** [nutzam/nutz#187]
打包成单独一个可以运行的jar，依赖包也直接打进去了，就出现下面的错误
Nutz: Fail to scan path 'rsrc:nutz-1.b.42-jdk6.jar'!
java.io.FileNotFoundException: rsrc:nutz-1.b.42-jdk6.jar (系统找不到指定的文件。
)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:127)
        at java.util.jar.JarFile.<init>(JarFile.java:135)
        at java.util.jar.JarFile.<init>(JarFile.java:72)
        at org.nutz.resource.impl.AbstractResourceScan.scanInJar(AbstractResourc
eScan.java:48)
        at org.nutz.resource.impl.LocalResourceScan.scanInJar(LocalResourceScan.
java:125)
        at org.nutz.resource.impl.LocalResourceScan.list(LocalResourceScan.java:
87)
        at org.nutz.resource.Scans.scanPackage(Scans.java:126)
        at org.nutz.resource.Scans.scanPackage(Scans.java:134)
        at org.nutz.castor.Castors.reload(Castors.java:165)
        at org.nutz.castor.Castors.resetPaths(Castors.java:109)
        at org.nutz.castor.Castors.<init>(Castors.java:142)
        at org.nutz.castor.Castors.<clinit>(Castors.java:38)
        at org.nutz.lang.Objs._convertMap(Objs.java:206)
        at org.nutz.lang.Objs.convertDeeply(Objs.java:156)
        at org.nutz.lang.Objs._convertObj(Objs.java:267)
        at org.nutz.lang.Objs.convertDeeply(Objs.java:160)
        at org.nutz.lang.Objs.convert(Objs.java:136)
        at org.nutz.json.Json.parse(Json.java:97)
        at org.nutz.json.Json.fromJson(Json.java:79)
        at org.nutz.dao.jdbc.Jdbcs.<clinit>(Jdbcs.java:54)
        at org.nutz.dao.impl.DaoSupport.setDataSource(DaoSupport.java:152)
        at org.nutz.dao.impl.NutDao.<init>(NutDao.java:86)
        at cn.blueram.rsa.utils.NutzUtil.getDao(NutzUtil.java:64)
        at cn.blueram.rsa.utils.LicenseDao.initTable(LicenseDao.java:11)
        at cn.blueram.rsa.key.GenUserMaxCount.main(GenUserMaxCount.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoa
der.java:56)
Nutz: Try to search in classpath : Gen.jar

**Comment by panyongchao** [comment]
怎么解决的呀？我也遇到这个问题

**Comment by wendal** [comment]
输出runnable jar的时候, 选 "extract required libraries"
