### ISSUE TITLE
1.b.45的EL报出如下错误

### ISSUE THREAD

**Issue by shinexiao** [nutzam/nutz#337]
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
	at java.util.ArrayList$Itr.next(ArrayList.java:791)
	at org.nutz.el.parse.Converter.parseItem(Converter.java:92)
	at org.nutz.el.parse.Converter.initItems(Converter.java:75)
	at org.nutz.el.arithmetic.ShuntingYard.parseToRPN(ShuntingYard.java:81)
	at org.nutz.el.El.eval(El.java:44)
	at org.javafans.print.service.impl.CraftService.calcPrint(CraftService.java:400)
	at org.javafans.print.service.impl.OrderService.calcPartVo(OrderService.java:2129)
	at org.javafans.print.action.OrderAction.calcParts(OrderAction.java:1048)
	at sun.reflect.GeneratedMethodAccessor1085.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at 
省略部分代码
我的代码主要是在Nutz Ioc  管理的Service里面 的方法里

public ResultVo<Object> calcPlate(double machineFee, double salaryDay,
			double eFee, double wFee, double flFee, double workDayFee,
			String expression) {
		ResultVo<Object> vo = new ResultVo<Object>();
		Context context = Lang.context();
		// 设置各种参数
		context.set("设备折旧费", machineFee);// 每天的机器折旧费
		context.set("人工费", salaryDay); // 每天的人工费

		context.set("电费", eFee);
		context.set("水费", wFee);

		context.set("辅料", flFee);// 辅料费用
		context.set("场地租用费", workDayFee); // 每天场地租用费

		Object val = El.eval(context, expression);
		vo.setT(val);
		return vo;
	}

系统是一个Nutz 的Web项目，发生异常时有5个人左右在同时测试出现。

**Comment by wendal** [comment]
事实上就是没吭声...
