### ISSUE TITLE
自定义SQL批处理时NutDao是否能自行检测param参数是否存在值

### ISSUE THREAD

**Issue by elkan1788** [nutzam/nutz#795]
#### 今天用自定义的SQL功能写了个批量处理数据的，Sqls的batch就类似JDBC中的PreparedStatement，起初没有去关心这个预处理的参数值会出现状况的，核心代码片段如下：

```java
// 短地址写入
String update = "UPDATE tablename SET SHORT_URL = @url WHERE INFO_ID = @id";
Sql u_sql = Sqls.create(update);
for (条件) {
    // 对当前页数据处理
	List<String[]> result = q_sql.getList(String[].class);
	int j=0;
	for (String[] arr : result) {
		// 获取短地址
		String url = preurl + arr[1] + "/";
		url = create(url.replaceAll("\\?",""));
		log.infof("%d: %s => %s", j, (preurl + arr[1] + "/"), url);
		if (!Lang.isEmpty(url)) {
			u_sql.params().set("url", url);
			u_sql.params().set("id", arr[0]);
			u_sql.addBatch();
		}
		j++;
	}

	dao.execute(u_sql);
	u_sql.clearBatch();
}
```

#### 上面的代码理论上应该没有问题的，所有的batch都添加的参数处理，每一次循环也clear了，可实际运行情况却是出现了下面的异常：

```java
org.nutz.dao.DaoException: !Nutz SQL Error: 'UPDATE tablename SET SHORT_URL =  WHERE INFO_ID = '
PreparedStatement: 
'UPDATE tablename SET SHORT_URL = ? WHERE INFO_ID = ?'
org.nutz.dao.DaoException: org.nutz.dao.DaoException: !Nutz SQL Error: 'UPDATE tablename SET SHORT_URL =  WHERE INFO_ID = '
PreparedStatement: 
'UPDATE tablename SET SHORT_URL = ? WHERE INFO_ID = ?'
at org.nutz.dao.impl.sql.run.NutDaoRunner.run(NutDaoRunner.java:76)
at org.nutz.dao.impl.DaoSupport._exec(DaoSupport.java:204)
at org.nutz.dao.impl.DaoSupport.execute(DaoSupport.java:182)
```

#### 上面的异常是说param的参数值有问题，后来自行增加了计数判断解决了。但希望官方可以把这块实现，这个场景的适用面还是很广泛的，已查阅了官方的API，并没有找到可以检测当前批处理中param是否有值的API，不知道是否可以增加或直接不执行空值批处理任务，谢谢。

**Comment by Wizzercn** [comment]
int类型就要转为int类型赋值啊，这个和nutz貌似无关。？

**Comment by elkan1788** [comment]
不是这个问题呀，看看下面的错误提示：

```java
 !Nutz SQL Error: 'UPDATE tablename SET SHORT_URL =  WHERE INFO_ID = '
```
表明这个预处理SQL没有赋值成功呀。

**Comment by zozoh** [comment]
增加技术判断？ 上面代码中的 `j` ?

**Comment by elkan1788** [comment]
不是，这个 **j** 是另有它用，上面的代码是产生异常的源码。

**Comment by zozoh** [comment]
改成这样试试:

```java
...
if(j>0){
    dao.execute(u_sql);
    u_sql.clearBatch();
}
...
```

**Comment by zozoh** [comment]
没问题就关了吧

**Comment by elkan1788** [comment]
这个BUG产生的根源知道了，下面那个addBatch的循环可能会有问题，业务逻辑问题。

```java
       if (!Lang.isEmpty(url)) {
            u_sql.params().set("url", url);
            u_sql.params().set("id", arr[0]);
            u_sql.addBatch();
        }

```
