### ISSUE TITLE
JsonAdaptor 为什么出错？

### ISSUE THREAD

**Issue by skynetbird** [nutzam/nutz#813]
前台页面传递Json对象，后台接收时出错。json格式应该没有问题，打印输出正常，异常提示信息的意思是传递的json数据格式有错误？不应该啊？求救。

异常信息如下：
Error@/workflow/ui/forward :
org.nutz.json.JsonException: !Json syntax error nearby [row:1,col:1 char 'r'], reason: 'Unexpect String = runactkey=fb1bc613c0a801982a788b76d8bdf744&endacts%5B0%5D%5Bactdefid%5D=DFGL_ZZ_GXSH_BMZR&endacts%5B0%5D%5Bactowners%5D%5B0%5D%5Buserid%5D=P0001&endacts%5B0%5D%5Bactowners%5D%5B0%5D%5Busername%5D=%E5%BC%A0%E7%91%9C&endacts%5B0%5D%5Bactowners%5D%5B0%5D%5Busertype%5D=PERSON'
	at org.nutz.json.impl.JsonTokenScan.readObject(JsonCompileImplV2.java:295)
	at org.nutz.json.impl.JsonTokenScan.read(JsonCompileImplV2.java:346)
	at org.nutz.json.impl.JsonCompileImplV2.parse(JsonCompileImplV2.java:25)
	at org.nutz.json.Json.fromJson(Json.java:40)
	at org.nutz.mvc.adaptor.JsonAdaptor.getReferObject(JsonAdaptor.java:35)
	at org.nutz.mvc.adaptor.AbstractAdaptor.adapt(AbstractAdaptor.java:200)
	at org.nutz.mvc.impl.processor.AdaptorProcessor.process(AdaptorProcessor.java:28)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.ActionFiltersProcessor.process(ActionFiltersProcessor.java:40)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.ModuleProcessor.process(ModuleProcessor.java:99)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.EncodingProcessor.process(EncodingProcessor.java:27)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.UpdateRequestAttributesProcessor.process(UpdateRequestAttributesProcessor.java:15)
	at org.nutz.mvc.impl.NutActionChain.doChain(NutActionChain.java:40)
	at org.nutz.mvc.impl.ActionInvoker.invoke(ActionInvoker.java:64)
	at org.nutz.mvc.ActionHandler.handle(ActionHandler.java:31)
	at org.nutz.mvc.NutFilter.doFilter(NutFilter.java:182)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:695)

前台调用代码如下：
	$.ajax({
		url: '/pams/workflow/ui/forward.action',
		type:'POST',
		dataType: 'json',
		data:json_forward,
		success: function(d)
		{
			console.log("forward success.");
		}
	});

Json对象(json_forward)内容如下：
 {"runactkey":"fb1bc613c0a801982a788b76d8bdf744","endacts":[{"actdefid":"DFGL_ZZ_GXSH_BMZR","actowners":[{"userid":"P0001","username":"张瑜","usertype":"PERSON"}]}]}

后台Action如下:
@IocBean
@At("/workflow/ui")
public class ForwardAction extends BaseAction{
	@At("/forward")
	@Ok("json")
	@AdaptBy(type=JsonAdaptor.class)
	public String main(VForward vo) throws Exception {
		System.out.println(vo);
		
		return "";
	}
}

**Comment by skynetbird** [comment]
搞定，试了试将 data:json_forward 改为 data:JSON.stringify(json_forward), 就OK了。
但，没想明白data:json_forward为什么不对啊，应该是可以的啊，算了，不想了，问UI高手怎么回事。

**Comment by wendal** [comment]
json_forward是个对象吧, jquery的知识了. 自动转to string的结果不是json
