### ISSUE TITLE
Json setLocked忽略字段不生效

### ISSUE THREAD

**Issue by Wizzercn** [nutzam/nutz#842]
@At
    @Ok("raw")
    public String listWaiting(@Param("userId") String userId, @Param("start") int start, @Param("num") int num) {
        Map<String, Object> map = new HashMap<String, Object>();
        try {
            TaskQuery query = taskService.createTaskQuery().taskCandidateOrAssigned(userId).orderByTaskCreateTime().desc();
            log.info("query::::"+query);
            log.info("total::::"+query.count());
            List<Task> doingTasks = query.listPage(start, num);
            long total = query.count();
            map.put("errcode", 0);
            map.put("errmsg", "");
            map.put("total", total);
            map.put("list", doingTasks);
        } catch (Exception e) {
            log.error("获取直接分配或者已经签收的任务出错", e);
            map.put("errcode", 1);
            map.put("errmsg", e.getMessage());
        }
        return Json.toJson(map,JsonFormat.compact().setLocked("^execution$"));
    }

2015-04-20 15:20:54,537 [INFO][org.nutz.lang.eject.EjectByGetter] - Fail to value by getter
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.nutz.lang.eject.EjectByGetter.eject(EjectByGetter.java:21)
        at org.nutz.json.entity.JsonEntityField.getValue(JsonEntityField.java:141)
        at org.nutz.json.impl.JsonRenderImpl.pojo2Json(JsonRenderImpl.java:246)
        at org.nutz.json.impl.JsonRenderImpl.render(JsonRenderImpl.java:115)
        at org.nutz.json.impl.JsonRenderImpl.coll2Json(JsonRenderImpl.java:379)
        at org.nutz.json.impl.JsonRenderImpl.render(JsonRenderImpl.java:106)
        at org.nutz.json.impl.JsonRenderImpl.appendPair(JsonRenderImpl.java:157)
        at org.nutz.json.impl.JsonRenderImpl.writeItem(JsonRenderImpl.java:298)
        at org.nutz.json.impl.JsonRenderImpl.map2Json(JsonRenderImpl.java:210)
        at org.nutz.json.impl.JsonRenderImpl.render(JsonRenderImpl.java:102)
        at org.nutz.json.Json.toJson(Json.java:225)
        at org.nutz.json.Json.toJson(Json.java:187)
        at com.auto.modules.wf.TestAction.listWaiting(TestAction.java:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.nutz.mvc.impl.processor.MethodInvokeProcessor.process(MethodInvokeProcessor.java:23)
        at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
        at org.nutz.mvc.impl.processor.AdaptorProcessor.process(AdaptorProcessor.java:33)
        at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
        at org.nutz.mvc.impl.processor.ActionFiltersProcessor.process(ActionFiltersProcessor.java:40)
        at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
        at org.nutz.mvc.impl.processor.ModuleProcessor.process(ModuleProcessor.java:113)
        at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
        at org.nutz.mvc.impl.processor.EncodingProcessor.process(EncodingProcessor.java:27)
        at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
        at org.nutz.mvc.impl.processor.UpdateRequestAttributesProcessor.process(UpdateRequestAttributesProcessor.java:15)
        at org.nutz.mvc.impl.NutActionChain.doChain(NutActionChain.java:40)
        at org.nutz.mvc.impl.ActionInvoker.invoke(ActionInvoker.java:67)
        at org.nutz.mvc.ActionHandler.handle(ActionHandler.java:31)
        at org.nutz.mvc.NutFilter.doFilter(NutFilter.java:182)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:947)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1852)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
        at org.activiti.engine.impl.persistence.entity.TaskEntity.getExecution(TaskEntity.java:319)
        at org.activiti.engine.impl.persistence.entity.TaskEntity.getExecution(TaskEntity.java:55)
        ... 52 more
2015-04-20 15:20:54,548 [WARN][org.nutz.mvc.impl.processor.FailProcessor] - Error@/test/listWaiting :
java.lang.RuntimeException: Fail to invoke getter org.activiti.engine.impl.persistence.entity.TaskEntity.'getExecution()' because [java.lang.NullPointerException]: null
        at org.nutz.lang.Lang.makeThrow(Lang.java:99)
        at org.nutz.lang.eject.EjectByGetter.eject(EjectByGetter.java:26)
        at org.nutz.json.entity.JsonEntityField.getValue(JsonEntityField.java:141)
        at org.nutz.json.impl.JsonRenderImpl.pojo2Json(JsonRenderImpl.java:246)
        at org.nutz.json.impl.JsonRenderImpl.render(JsonRenderImpl.java:115)
        at org.nutz.json.impl.JsonRenderImpl.coll2Json(JsonRenderImpl.java:379)
        at org.nutz.json.impl.JsonRenderImpl.render(JsonRenderImpl.java:106)
        at org.nutz.json.impl.JsonRenderImpl.appendPair(JsonRenderImpl.java:157)
        at org.nutz.json.impl.JsonRenderImpl.writeItem(JsonRenderImpl.java:298)
        at org.nutz.json.impl.JsonRenderImpl.map2Json(JsonRenderImpl.java:210)
        at org.nutz.json.impl.JsonRenderImpl.render(JsonRenderImpl.java:102)
        at org.nutz.json.Json.toJson(Json.java:225)
        at org.nutz.json.Json.toJson(Json.java:187)
        at com.auto.modules.wf.TestAction.listWaiting(TestAction.java:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.nutz.mvc.impl.processor.MethodInvokeProcessor.process(MethodInvokeProcessor.java:23)
        at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
        at org.nutz.mvc.impl.processor.AdaptorProcessor.process(AdaptorProcessor.java:33)
        at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
        at org.nutz.mvc.impl.processor.ActionFiltersProcessor.process(ActionFiltersProcessor.java:40)
        at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
        at org.nutz.mvc.impl.processor.ModuleProcessor.process(ModuleProcessor.java:113)
        at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
        at org.nutz.mvc.impl.processor.EncodingProcessor.process(EncodingProcessor.java:27)
        at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
        at org.nutz.mvc.impl.processor.UpdateRequestAttributesProcessor.process(UpdateRequestAttributesProcessor.java:15)
        at org.nutz.mvc.impl.NutActionChain.doChain(NutActionChain.java:40)
        at org.nutz.mvc.impl.ActionInvoker.invoke(ActionInvoker.java:67)
        at org.nutz.mvc.ActionHandler.handle(ActionHandler.java:31)
        at org.nutz.mvc.NutFilter.doFilter(NutFilter.java:182)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:947)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1852)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)

**Comment by wendal** [comment]
pojo2Json 里面是先取值,后判断是否忽略,所以无法忽略getter出错的情况.

**Comment by Wizzercn** [comment]
能否在getter出错的时候忽略呢,毕竟很难确定那些属性不知道在何时会有用.

**Comment by wendal** [comment]
通过 548e4de537e8c2e96c346c66c8dfef18aaaff5cc 解决
