### ISSUE TITLE
sqlite数据库不支持savepoint，使用事务的时候出错

### ISSUE THREAD

**Issue by chengjie** [nutzam/nutz#864]
org.nutz.dao.DaoException: java.sql.SQLException: unsupported by SQLite: savepoints
	at org.nutz.dao.impl.sql.run.NutDaoRunner.run(NutDaoRunner.java:50) ~[nutz-1.b.52.jar:na]
	at org.nutz.dao.impl.DaoSupport._exec(DaoSupport.java:205) ~[nutz-1.b.52.jar:na]
	at org.nutz.dao.impl.EntityOperator.exec(EntityOperator.java:50) ~[nutz-1.b.52.jar:na]
	at org.nutz.dao.impl.NutDao.update(NutDao.java:237) ~[nutz-1.b.52.jar:na]

**Comment by ywjno** [comment]
用的 sqlite 的 jdbc 驱动支持 savepoint 功能么

**Comment by wendal** [comment]
sqlite这种数据库就别想着事务了
