### ISSUE TITLE
@Many(target = Pet.class, field = "masterId", key="name") key的含义

### ISSUE THREAD

**Issue by ming300** [nutzam/nutz#868]
mysql 环境下,这个key指向的字段是 当前的对象 Master  还是 targe的Pet对象,

```
@Table("t_master")
public class Master extends Pojo {
    @Many(target = Pet.class, field = "masterId", key="name")
    private Map<String,Pet> pets;
```
文档中写的是
http://nutzam.com/core/dao/links_many.html

```
key 所指的字段 name，表示 Pet 对象的 name 字段， Nutz.Dao 将采用这个字段作为 Map 的键
为目标 POJO 类的 JAVA 字段名
大小写敏感
``

如果按照文档的配置会报错!
`java.lang.RuntimeException: Fail to find hostField for @Many(field=masterId) 'pets' : class Master <=>class Pet
	at org.nutz.lang.Lang.makeThrow(Lang.java:99)
	at org.nutz.dao.impl.entity.field.ManyLinkField.<init>(ManyLinkField.java:51)
	at org.nutz.dao.impl.entity.AnnotationEntityMaker.make(AnnotationEntityMaker.java:264)
	at org.nutz.dao.impl.EntityHolder.getEntity(EntityHolder.java:65)
	at org.nutz.dao.impl.NutDao.getEntity(NutDao.java:638)

**Comment by wendal** [comment]
在@Many中, field 是Pet上的属性,

@One 刚好相反

原因嘛? 我觉得可以找@zozoh问问
