### ISSUE TITLE
线上报出这种错误，我是不是被攻击了

### ISSUE THREAD

**Issue by xbl** [nutzam/nutz#900]
[2015-07-14 19:37:33,791] ERROR com.hdl.gup.view.FailView org.nutz.json.JsonException: !Json syntax error nearby [row:1,col:1 char ' '], reason: 'Unexpect String = "vV W &V'" "vV5 V" C ' at org.nutz.json.impl.JsonTokenScan.readObject(JsonCompileImplV2.java:295) at org.nutz.json.impl.JsonTokenScan.read(JsonCompileImplV2.java:351) at org.nutz.json.impl.JsonCompileImplV2.parse(JsonCompileImplV2.java:25) at org.nutz.json.Json.fromJson(Json.java:40) at org.nutz.mvc.adaptor.JsonAdaptor.getReferObject(JsonAdaptor.java:35) at org.nutz.mvc.adaptor.AbstractAdaptor.adapt(AbstractAdaptor.java:211) at org.nutz.mvc.impl.processor.AdaptorProcessor.process(AdaptorProcessor.java:28) at org.nutz.mvc.impl.processor.AbstractProcessor.do

**Comment by wendal** [comment]
也许吧

**Comment by wendal** [comment]
这种问题, 如果不是自己的代码生成的,那就判定为其他恶意访问了

**Comment by xbl** [comment]
好吧，一到高峰期就报这种乱七八糟的字符串，谢谢啦；
