### ISSUE TITLE
当 postgresql 中某字段类型为 json 时无法插入数据

### ISSUE THREAD

**Issue by ywjno** [nutzam/nutz#921]
直接上代码
```java
public class PostgreSQLJSONTest {

    public static final void main(String[] args) throws IOException, SQLException, ClassNotFoundException {
        SimpleDataSource ds = new SimpleDataSource();
        ds.setDriverClassName("org.postgresql.Driver");
        ds.setJdbcUrl("jdbc:postgresql://127.0.0.1:5432/nutztest");
        ds.setUsername("ywjno");

        DaoUp.me().setDataSource(ds);
        Dao dao = DaoUp.me().dao();

        String tableName = "PostgreSQLJSONTest";
        if (!dao.exists(tableName)) {
            dao.execute(Sqls.create("create table " + tableName + " (id int, data json)"));
        }

        NutMap data = new NutMap().setv("name", "ywjno");

        Sql sql = Sqls.create("insert into $table_name (id, data) values (1, @data)");
        sql.vars().set("table_name", tableName);
        sql.params().set("data", Json.toJson(data, JsonFormat.tidy()));
        dao.execute(sql);

        DaoUp.me().close();
    }
}
```

log 如下
```
ALL Nutz Log via Log4jLogAdapter
2015-08-11 12:58:51,775 [main] INFO  org.nutz.log.Logs - Nutz is licensed under the Apache License, Version 2.0 .
Report bugs : https://github.com/nutzam/nutz/issues
2015-08-11 12:58:51,824 [main] WARN  org.nutz.dao.impl.SimpleDataSource - SimpleDataSource is use for Test/Attempt, NOT Using in Production environment!
2015-08-11 12:58:51,824 [main] WARN  org.nutz.dao.impl.SimpleDataSource - SimpleDataSource is NOT a Connection Pool, So it is slow but safe for debug/study
2015-08-11 12:58:52,046 [main] DEBUG org.nutz.castor.Castors - Using 91 castor for Castors
2015-08-11 12:58:52,067 [main] INFO  org.nutz.filepool.NutFilePool - Init file-pool by: /Users/ywjno/.nutz/tmp/dao/ [200000]
2015-08-11 12:58:52,068 [main] DEBUG org.nutz.filepool.NutFilePool - file-pool.home: '/Users/ywjno/.nutz/tmp/dao'
2015-08-11 12:58:52,074 [main] INFO  org.nutz.filepool.NutFilePool - file-pool.cursor: 14
2015-08-11 12:58:52,094 [main] DEBUG org.nutz.dao.jdbc.Jdbcs - Jdbcs init complete
2015-08-11 12:58:52,096 [main] INFO  org.nutz.dao.jdbc.Jdbcs - Get Connection from DataSource for JdbcExpert
2015-08-11 12:58:52,295 [main] DEBUG org.nutz.dao.impl.DaoSupport - JDBC Driver --> PostgreSQL 9.3 JDBC4 (build 1102)
2015-08-11 12:58:52,297 [main] DEBUG org.nutz.dao.impl.DaoSupport - JDBC Name   --> PostgreSQL Native Driver
2015-08-11 12:58:52,298 [main] DEBUG org.nutz.dao.impl.DaoSupport - JDBC URL    --> jdbc:postgresql://127.0.0.1:5432/nutztest
2015-08-11 12:58:52,300 [main] DEBUG org.nutz.dao.impl.DaoSupport - Database info --> PSQL:[PostgreSQL - 9.4.4]
2015-08-11 12:58:52,432 [main] DEBUG org.nutz.dao.impl.sql.run.NutDaoExecutor - insert into PostgreSQLJSONTest (id, data) values (1, '{"name":"ywjno"}')
2015-08-11 12:58:52,449 [main] DEBUG org.nutz.dao.impl.sql.run.NutDaoExecutor - SQLException
org.postgresql.util.PSQLException: ERROR: column "data" is of type json but expression is of type character varying
  建议：You will need to rewrite or cast the expression.
  位置：54
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:412)
	at org.nutz.dao.impl.sql.run.NutDaoExecutor._runPreparedStatement(NutDaoExecutor.java:266)
	at org.nutz.dao.impl.sql.run.NutDaoExecutor.exec(NutDaoExecutor.java:81)
	at org.nutz.dao.impl.DaoSupport$DaoExec.invoke(DaoSupport.java:263)
	at org.nutz.dao.impl.sql.run.NutDaoRunner.run(NutDaoRunner.java:64)
	at org.nutz.dao.impl.DaoSupport._exec(DaoSupport.java:218)
	at org.nutz.dao.impl.DaoSupport.execute(DaoSupport.java:196)
	at org.nutz.dao.impl.NutDao.execute(NutDao.java:973)
	at PostgreSQLJSONTest.main(PostgreSQLJSONTest.java:42)
Exception in thread "main" org.nutz.dao.DaoException: !Nutz SQL Error: 'insert into PostgreSQLJSONTest (id, data) values (1, '{"name":"ywjno"}')'
PreparedStatement: 
'insert into PostgreSQLJSONTest (id, data) values (1, ?)'
CaseMessage=ERROR: column "data" is of type json but expression is of type character varying
  建议：You will need to rewrite or cast the expression.
  位置：54
	at org.nutz.dao.impl.sql.run.NutDaoExecutor.exec(NutDaoExecutor.java:95)
	at org.nutz.dao.impl.DaoSupport$DaoExec.invoke(DaoSupport.java:263)
	at org.nutz.dao.impl.sql.run.NutDaoRunner.run(NutDaoRunner.java:64)
	at org.nutz.dao.impl.DaoSupport._exec(DaoSupport.java:218)
	at org.nutz.dao.impl.DaoSupport.execute(DaoSupport.java:196)
	at org.nutz.dao.impl.NutDao.execute(NutDao.java:973)
	at PostgreSQLJSONTest.main(PostgreSQLJSONTest.java:42)
Caused by: org.postgresql.util.PSQLException: ERROR: column "data" is of type json but expression is of type character varying
  建议：You will need to rewrite or cast the expression.
  位置：54
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:412)
	at org.nutz.dao.impl.sql.run.NutDaoExecutor._runPreparedStatement(NutDaoExecutor.java:266)
	at org.nutz.dao.impl.sql.run.NutDaoExecutor.exec(NutDaoExecutor.java:81)
	... 6 more
```

 在数据库中直接运行 `insert into PostgreSQLJSONTest (id, data) values (1, '{"name":"ywjno"}')`这句  sql 语句的话没问题

**Comment by ywjno** [comment]
直接把 sql 语句给改成如下就行了
```java
Sql sql = Sqls.create("insert into $table_name (id, data) values (1, to_json(@data::json))");
```
但是，用如下语句就又不行了
```java
dao.insert(tableName, Chain.make("id", 100).add("data", Json.toJson(data, JsonFormat.tidy())));
```

**Comment by wendal** [comment]
解决不了的啦, 自定义sql啦
