### ISSUE TITLE
NutIoc读取 js 文件时无法加载继承了PropertiesProxy类的之类

### ISSUE THREAD

**Issue by ywjno** [nutzam/nutz#922]
比如有那么一个类，
```java
package xyz.abc;

public class AppConfig extends PropertiesProxy {
    private static final String MACRO_INCLUDE = "$include";

    public AppConfig(String path) {
        super(path);
        joinByKey(MACRO_INCLUDE);
    }
}
```

然后 conf/ioc.js 文件如下
```js
var ioc = {
  // 读取配置文件
  config : {
    type : "xyz.abc.AppConfig",
    fields : {
      paths : ["app.properties"]
    }
  }
}
```

调用代码为
```java
public class App {
    public static void main(String[] args) {
        Ioc ioc = new NutIoc(new JsonLoader("conf/ioc.js"));
        AppConfig config = ioc.get(AppConfig.class, "config");
    }
}
```

提示如下错误
```
Exception in thread "main" org.nutz.ioc.IocException: Fail to born 'xyz.abc.AppConfig'
 by args: [] FAIL to create Ioc Bean name=[config] 
beacase [Fail to born 'xyz.abc.AppConfig'
 by args: []]
	at org.nutz.ioc.impl.ObjectMakerImpl.make(ObjectMakerImpl.java:141)
	at org.nutz.ioc.impl.NutIoc.get(NutIoc.java:196)
	at org.nutz.ioc.impl.NutIoc.get(NutIoc.java:221)
	at com.malaneo.App.main(App.java:24)
Caused by: org.nutz.lang.born.BorningException: Fail to born 'xyz.abc.AppConfig'
 by args: []
	at org.nutz.lang.Mirror.getBorning(Mirror.java:931)
	at org.nutz.ioc.impl.ObjectMakerImpl.make(ObjectMakerImpl.java:105)
	... 3 more
```

而把 conf/ioc.js 文件跟 main 方法改成如下内容
```js
var ioc = {
  // 读取配置文件
  config : {
    type : "org.nutz.ioc.impl.PropertiesProxy",
    fields : {
      paths : ["app.properties"]
    }
  }
}
```

```java
public class App {
    public static void main(String[] args) {
        Ioc ioc = new NutIoc(new JsonLoader("conf/ioc.js"));
        PropertiesProxy config = ioc.get(PropertiesProxy.class, "config");
    }
}
```
则不会出错

这里必须只能使用 PropertiesProxy 类才能实现 Ioc 自动读取 properties 文件么？？

**Comment by wendal** [comment]
问题在于AppConfig的构造方法

PropertiesProxy 的构造方法参数是String ... paths , 所以无需参数也能new

而 AppConfig是String path, 必须带参数


另外,  PropertiesProxy 是一个非常独立的类, 与Ioc没有关联性. Ioc不认识PropertiesProxy , 而PropertiesProxy 也不认识Ioc

**Comment by ywjno** [comment]
哦。。。貌似知道怎么改了，给AppConfig加上构造函数就行了
