### ISSUE TITLE
Sqls.create() 执行存储过程的问题

### ISSUE THREAD

**Issue by wangyingdong** [nutzam/nutz#981]
环境版本1.53,sqlserver2008
执行存储过程的问题
Sql sql = Sqls.create("call getMessage (@channel,@count)");
sql.params().set("channel", 100);
sql.params().set("count", 100);

sql.setCallback(Sqls.callback.entities());
sql.setEntity(smsDao.getEntity(Message.class));
smsDao.execute(sql);

执行出现异常：
![1](https://cloud.githubusercontent.com/assets/924258/11331921/d046aef2-91fb-11e5-9720-84e858e9d6b0.png)

异常信息：
java.sql.SQLException: Invalid parameter index 2.
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.getParameter(JtdsPreparedStatement.java:340)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.setParameter(JtdsPreparedStatement.java:409)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.setInt(JtdsPreparedStatement.java:578)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setInt(FilterChainImpl.java:2773)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setInt(FilterAdapter.java:1237)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setInt(FilterChainImpl.java:2770)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.setInt(PreparedStatementProxyImpl.java:341)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.setInt(DruidPooledPreparedStatement.java:310)
	at org.nutz.dao.jdbc.Jdbcs$Adaptor$4.set(Jdbcs.java:320)
	at org.nutz.dao.impl.sql.run.NutDaoExecutor._runExec(NutDaoExecutor.java:123)
	at org.nutz.dao.impl.sql.run.NutDaoExecutor.exec(NutDaoExecutor.java:59)
	at org.nutz.dao.impl.DaoSupport$DaoExec.invoke(DaoSupport.java:264)
	at org.nutz.dao.impl.sql.run.NutDaoRunner.run(NutDaoRunner.java:64)
	at org.nutz.dao.impl.DaoSupport._exec(DaoSupport.java:219)
	at org.nutz.dao.impl.DaoSupport.execute(DaoSupport.java:197)
	at org.nutz.dao.impl.NutDao.execute(NutDao.java:967)

改成 Sql sql = Sqls.create("exec getMessage (@channel,@count)"); 可以正确执行。

**Comment by wangyingdong** [comment]
改成 Sql sql = Sqls.create("exec getMessage (@channel,@count)"); 可以正确执行。

**Comment by zozoh** [comment]
SqlServer 不太熟，难道 "call xxxx" 不能支持  `preparedStatement` ??

你换成 :

```java
Sql sql = Sqls.create("call getMessage ($channel,$count)");
sql.vars().set("channel", 100);
sql.vars().set("count", 100);
```

看看能不能执行过？

**Comment by wangyingdong** [comment]
换成
Sql sql = Sqls.create("call getMessage ($channel,$count)");
sql.vars().set("channel", 100);
sql.vars().set("count", 100);
一样出错了。
![2](https://cloud.githubusercontent.com/assets/924258/11332199/7d526616-91fe-11e5-85cf-2d794561d38d.jpg)


DEBUG [org.nutz.dao.impl.sql.run.NutDaoExecutor] - SQLException
java.sql.SQLException: '100' 附近有语法错误。
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:368)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2820)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2258)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:632)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:584)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:546)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:561)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2931)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2929)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:131)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
	at org.nutz.dao.impl.sql.run.NutDaoExecutor._runExec(NutDaoExecutor.java:128)
	at org.nutz.dao.impl.sql.run.NutDaoExecutor.exec(NutDaoExecutor.java:59)
	at org.nutz.dao.impl.DaoSupport$DaoExec.invoke(DaoSupport.java:264)
	at org.nutz.dao.impl.sql.run.NutDaoRunner.run(NutDaoRunner.java:64)
	at org.nutz.dao.impl.DaoSupport._exec(DaoSupport.java:219)
	at org.nutz.dao.impl.DaoSupport.execute(DaoSupport.java:197)
	at org.nutz.dao.impl.NutDao.execute(NutDao.java:967)

**Comment by wendal** [comment]
改成Call试试，可能没处理大小写，没识别对

**Comment by wangyingdong** [comment]
Sql sql = Sqls.create("Call getMessage (@channel,@count)");
改成Call试试，一样出错。

![1](https://cloud.githubusercontent.com/assets/924258/11354395/1e243498-9286-11e5-9306-981a088a9b56.jpg)


java.sql.SQLException: Invalid parameter index 2.
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.getParameter(JtdsPreparedStatement.java:340)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.setParameter(JtdsPreparedStatement.java:409)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.setInt(JtdsPreparedStatement.java:578)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setInt(FilterChainImpl.java:2773)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setInt(FilterAdapter.java:1237)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setInt(FilterChainImpl.java:2770)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.setInt(PreparedStatementProxyImpl.java:341)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.setInt(DruidPooledPreparedStatement.java:310)
	at org.nutz.dao.jdbc.Jdbcs$Adaptor$4.set(Jdbcs.java:320)
	at org.nutz.dao.impl.sql.run.NutDaoExecutor._runExec(NutDaoExecutor.java:123)
	at org.nutz.dao.impl.sql.run.NutDaoExecutor.exec(NutDaoExecutor.java:59)
	at org.nutz.dao.impl.DaoSupport$DaoExec.invoke(DaoSupport.java:264)
	at org.nutz.dao.impl.sql.run.NutDaoRunner.run(NutDaoRunner.java:64)
	at org.nutz.dao.impl.DaoSupport._exec(DaoSupport.java:219)
	at org.nutz.dao.impl.DaoSupport.execute(DaoSupport.java:197)
	at org.nutz.dao.impl.NutDao.execute(NutDao.java:967)

**Comment by wendal** [comment]
都是入参吗?

**Comment by wangyingdong** [comment]
都是传参数的，也是有返回值的。

**Comment by wendal** [comment]
奇怪, 先用jdbc吧

**Comment by wangyingdong** [comment]
现在用的是
 Sql sql = Sqls.create("exec getMessage (@channel,@count)"); 可以正确执行。

**Comment by zozoh** [comment]
算是 FAQ 吧

**Comment by wendal** [comment]
1.r.58 ok的
