### ISSUE TITLE
El 表达式，应该支持更宽泛的判断

### ISSUE THREAD

**Issue by zozoh** [nutzam/nutz#983]
```java
Context c = Lang.context("{se : {id:'aabbcc'}}");
Object re = El.eval(c, "se.id && se.id.length()==0");
System.out.println(re);
```

执行会报错

```
Exception in thread "main" org.nutz.el.ElException: 操作数类型错误!
	at org.nutz.el.opt.logic.AndOpt.calculate(AndOpt.java:19)
	at org.nutz.el.arithmetic.RPN.calculate(RPN.java:55)
	at org.nutz.el.arithmetic.RPN.calculate(RPN.java:46)
	at org.nutz.el.El.eval(El.java:45)
	at zzh.ZZHMain.main(ZZHMain.java:42)
```

应该容忍更多的情况

**Comment by zozoh** [comment]
应该修正了
