### ISSUE TITLE
nutz不能在日文OS上运行

### ISSUE THREAD

**Issue by majong** [nutzam/nutz#986]
我写的server在英文、中文windows OS可以正常运行，但是安装在日文Windows7上，服务就无法启动了，mvc.log的输出为：
Caused by: org.nutz.ioc.IocException: create ioc bean fail name=esignageDao ioc define:
{
   "type" :"org.nutz.dao.impl.NutDao",
   "singleton" :true,
   "args" :[{
      "type" :"refer",
      "value" :"esignageDataSource"
   }],
   "fields" :[],
   "scope" :"app"
}
	at org.nutz.ioc.impl.ObjectMakerImpl.make(ObjectMakerImpl.java:132)
	at org.nutz.ioc.impl.NutIoc.get(NutIoc.java:194)
	at org.nutz.ioc.val.ReferValue.get(ReferValue.java:24)
	at org.nutz.ioc.impl.ObjectMakerImpl.make(ObjectMakerImpl.java:73)
	... 44 more
Caused by: org.nutz.lang.born.BorningException: Fail to born 'org.nutz.dao.impl.NutDao'
 by args: [
  @(com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 10, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, dataSourceName -> 2sa0yo9dnz4fw1f35nyn|5c062a59, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.postgresql.Driver, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> 2sa0yo9dnz4fw1f35nyn|5c062a59, idleConnectionTestPeriod -> 0, initialPoolSize -> 20, jdbcUrl -> jdbc:postgresql://127.0.0.1:5433/esignage, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 3600, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 30, maxPoolSize -> 500, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 20, numHelperThreads -> 3, numThreadsAwaitingCheckoutDefaultUser -> 0, preferredTestQuery -> null, properties -> {user=******, password=******}, propertyCycle -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> true, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false ])] becasue:
java.lang.NoClassDefFoundError: Could not initialize class org.nutz.dao.jdbc.Jdbcs
	at org.nutz.lang.born.ConstructorBorning.born(ConstructorBorning.java:19)
	at org.nutz.ioc.weaver.DefaultWeaver.born(DefaultWeaver.java:67)
	at org.nutz.ioc.impl.ObjectMakerImpl.make(ObjectMakerImpl.java:103)
	... 47 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.nutz.dao.jdbc.Jdbcs
	at org.nutz.dao.impl.DaoSupport.setDataSource(DaoSupport.java:156)
	at org.nutz.dao.impl.NutDao.<init>(NutDao.java:116)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at org.nutz.lang.born.ConstructorBorning.born(ConstructorBorning.java:17)
	... 49 more
[http-apr-80-exec-17]11-30 14:40:09-Error happend during start serivce!

**Comment by wendal** [comment]
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.nutz.dao.jdbc.Jdbcs
```

但没看出无法初始化的原因...

**Comment by majong** [comment]
似乎是日文系统下不允许创建前面有“.”的目录，所以.nutz/tmp/dao创建不出来。

**Comment by wendal** [comment]
那改一下nutz_jdbc_experts.js里面的路径, 

拷贝一份到src下,改一下就行

**Comment by ywjno** [comment]
日文系统是可以的，我都在 日文xp 的下面跑过代码

**Comment by majong** [comment]
修改nutz_jdbc_experts.js，将“.nuz"改为"nuz"也不行.
报错在32行：    	String home = config.get("pool-home").toString();

我以前使用的是很老的版本，2010年5月的。现在迁移到1.b.53。

**Comment by majong** [comment]
找到原因了,问题出在nutz_jdbc_experts.js
	config : {
	// 默认的 Clob 以及 Blog 临时目录
	"pool-home" : "~/.nutz/tmp/dao/",
	// 临时目录大小，0 为不限大小
	"pool-max" : 200000,
	// Mysql 特殊配置
	"mysql-engine" : "InnoDB",
	// GBase 特殊配置
	"gbase-engine" : "GsDB"
	// ～ 配置信息结束
	}
因为有中文字符在json的注释中，造成json解析不到pool-max和pool-home
只要去掉注释中的“录”和“小”，就没有问题了。
最后我将注释改为：
	// default temp folder for Clob and Blog
	"pool-home" : "~/.nutz/tmp/dao/",
	// temp folder size，0 means no limitation
	"pool-max" : 200000,

**Comment by wendal** [comment]
恩, 解决了就好
